### ISSUE TITLE
SDL 2: Numpad keys don't work

### ISSUE THREAD

**Issue by grorp** [minetest/irrlicht#215] opened 2023-07-03 12:39 UTC
both Linux and Windows
Minetest commit minetest/minetest@25ef8f39341724550c3af19873e7f324a5a57251
IrrlichtMt commit 83699a835df2c7363ae856ee128fb2409743f65d

With `USE_SDL2=FALSE`, Minetest handles numpad input correctly: When numlock is enabled, I can use the numpad's number keys to select items in the hotbar, and the numpad's <kbd>+</kbd> and <kbd>-</kbd> keys to increase and decrease the view range.

With `USE_SDL2=TRUE`, Minetest doesn't respond at all when you press keys on the numpad, regardless of whether numlock is enabled or not.

**Comment by numberZero** [comment] 2023-07-05 20:32
Duplicate of #207.

**Closed** 2023-07-05 20:40 UTC
